/**
 * This file is automatically generated.
 * DO NOT EDIT manually
 */

export const controllers = {
  Categories: () => import('#controllers/categories_controller'),
  Depenses: () => import('#controllers/depenses_controller'),
  DepensesImport: () => import('#controllers/depenses_import_controller'),
  NewAccount: () => import('#controllers/new_account_controller'),
  Session: () => import('#controllers/session_controller'),
}
